version: '3.7'

x-user-args:
  &user-args
  APP_USER: ${APP_USER}
  APP_GROUP: ${APP_GROUP}
  APP_USER_ID: ${APP_USER_ID}
  APP_GROUP_ID: ${APP_GROUP_ID}

x-app-volume: &app-volume ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        <<: *user-args
    volumes:
      - *app-volume
    depends_on:
      - database
    command: >
      bash -c "php-fpm"

  nginx:
    image: nginx
    restart: always
    volumes:
      - *app-volume
      - "./configs/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - app
      - database

  database:
    image: mysql
    restart: always
    environment:
      - MYSQL_PASSWORD=tT7jN0oX0f
      - MYSQL_DATABASE=art-search
      - MYSQL_USER=manticore
      - MYSQL_ROOT_PASSWORD=tT7jN0oX0f111
    # volumes:
    #   # - 'database:/var/lib/mysql/data'

  manticore:
    image: manticoresearch/manticore
    environment:
      - EXTRA=1
    restart: always
    ports:
      - 9312:9312
      - 9306:9306
      - 9308:9308
    volumes:
      - ./manticore.conf:/etc/manticoresearch/manticore.conf

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 28082:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=100096K

